### ISSUE TITLE
离线Web模版初始化失败

### ISSUE THREAD

**Issue by kangear** [TencentDingdang/WebViewSDK#1]
Android 6.0
红米Note 3
版本：1.0

```logcat
09-24 16:43:04.865 28735-28735/? I/art: Late-enabling -Xcheck:jni
09-24 16:43:04.891 28735-28735/? D/TidaProvider: TidaProvider()
09-24 16:43:04.896 28735-28735/? W/ReflectionUtils: java.lang.NoSuchMethodException: android.os.MessageQueue#enableMonitor()#bestmatch
        at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:338)
        at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:375)
        at miui.util.ReflectionUtils.callMethod(ReflectionUtils.java:800)
        at miui.util.ReflectionUtils.tryCallMethod(ReflectionUtils.java:818)
        at android.os.BaseLooper.enableMonitor(BaseLooper.java:47)
        at android.os.Looper.prepareMainLooper(Looper.java:111)
        at android.app.ActivityThread.main(ActivityThread.java:5597)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
09-24 16:43:04.928 28735-28735/com.tencent.offlinewebdemo W/System: ClassLoader referenced unknown path: /data/app/com.tencent.offlinewebdemo-2/lib/arm64
09-24 16:43:04.941 28735-28735/com.tencent.offlinewebdemo W/System.err: java.io.FileNotFoundException: /storage/emulated/0/tencent/qrom/log_cfg/log_switch.ini: open failed: ENOENT (No such file or directory)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at qrom.component.log.a.d.a(SourceFile:254)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at qrom.component.log.a.b.<init>(SourceFile:78)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at qrom.component.log.a.b.a(SourceFile:95)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at qrom.component.log.QRomLog.v(SourceFile:82)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at com.tencent.ai.tvs.base.log.DMLog.pv(Unknown Source)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at com.tencent.ai.tvs.env.EnvManager.setEnv(Unknown Source)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at com.tencent.ai.tvs.env.EnvManager.init(Unknown Source)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at com.tencent.ai.tvs.dmsdk.demo.App.onCreate(App.java:11)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4839)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:154)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1464)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at android.os.Looper.loop(Looper.java:157)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5615)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at libcore.io.Posix.open(Native Method)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)
09-24 16:43:04.942 28735-28735/com.tencent.offlinewebdemo W/System.err: 	... 19 more
09-24 16:43:04.944 28735-28735/com.tencent.offlinewebdemo V/EnvManager: setEnv: pre = null, new = FORMAL
09-24 16:43:04.983 28735-28735/com.tencent.offlinewebdemo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-24 16:43:05.002 28735-28735/com.tencent.offlinewebdemo D/AccessibilityManager: current package=com.tencent.offlinewebdemo, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=false, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
09-24 16:43:05.005 28735-28765/com.tencent.offlinewebdemo W/System: ClassLoader referenced unknown path: /system/app/MiuiContentCatcher/lib/arm64
09-24 16:43:05.011 28735-28735/com.tencent.offlinewebdemo I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
09-24 16:43:05.011 28735-28735/com.tencent.offlinewebdemo I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
09-24 16:43:05.099 28735-28769/com.tencent.offlinewebdemo D/OfflineWebManager: file not found exception!
09-24 16:43:05.099 28735-28769/com.tencent.offlinewebdemo W/System.err: java.io.FileNotFoundException: sdcard/nativeweb/webtemplate/nativewebconfig.xml: open failed: ENOENT (No such file or directory)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:103)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at com.tencent.ai.tvs.offlinewebtemplate.OfflineWebManager.a(SourceFile:358)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at com.tencent.ai.tvs.offlinewebtemplate.OfflineWebManager.a(SourceFile:37)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at com.tencent.ai.tvs.offlinewebtemplate.OfflineWebManager$1.a(SourceFile:119)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at com.tencent.ai.tvs.offlinewebtemplate.OfflineWebManager$1.doInBackground(SourceFile:116)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-24 16:43:05.100 28735-28769/com.tencent.offlinewebdemo W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-24 16:43:05.101 28735-28769/com.tencent.offlinewebdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-24 16:43:05.101 28735-28769/com.tencent.offlinewebdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-24 16:43:05.101 28735-28769/com.tencent.offlinewebdemo W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-24 16:43:05.101 28735-28769/com.tencent.offlinewebdemo W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
09-24 16:43:05.101 28735-28769/com.tencent.offlinewebdemo W/System.err:     at libcore.io.Posix.open(Native Method)
09-24 16:43:05.101 28735-28769/com.tencent.offlinewebdemo W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
09-24 16:43:05.101 28735-28769/com.tencent.offlinewebdemo W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)
09-24 16:43:05.101 28735-28769/com.tencent.offlinewebdemo W/System.err: 	... 12 more
09-24 16:43:05.102 28735-28735/com.tencent.offlinewebdemo D/OfflineWebPkgUpdate: localVersionCode =1
09-24 16:43:05.102 28735-28735/com.tencent.offlinewebdemo D/OfflineWebPkgUpdate: reqNativeWebDownloadPkg call req
09-24 16:43:05.111 28735-28771/com.tencent.offlinewebdemo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-24 16:43:05.138 28735-28771/com.tencent.offlinewebdemo I/Adreno: QUALCOMM build                   : a7823f5, I59a6815413
    Build Date                       : 09/23/16
    OpenGL ES Shader Compiler Version: XE031.07.00.00
    Local Branch                     : mybranch22028469
    Remote Branch                    : quic/LA.BR.1.3.3_rb2.26
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
09-24 16:43:05.142 28735-28771/com.tencent.offlinewebdemo I/OpenGLRenderer: Initialized EGL, version 1.4
09-24 16:43:05.149 28735-28735/com.tencent.offlinewebdemo I/WebViewFactory: Loading com.google.android.webview version 71.0.3578.99 (code 357809950)
09-24 16:43:05.239 28735-28735/com.tencent.offlinewebdemo I/cr_LibraryLoader: Time to load native libraries: 1 ms (timestamps 118-119)
09-24 16:43:05.255 28735-28735/com.tencent.offlinewebdemo I/chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
09-24 16:43:05.255 28735-28735/com.tencent.offlinewebdemo I/cr_LibraryLoader: Expected native library version number "71.0.3578.99", actual native library version number "71.0.3578.99"
09-24 16:43:05.265 28735-28735/com.tencent.offlinewebdemo I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
09-24 16:43:05.324 28735-28789/com.tencent.offlinewebdemo W/cr_CrashFileManager: /data/user/0/com.tencent.offlinewebdemo/cache/WebView/Crash Reports does not exist or is not a directory
09-24 16:43:05.373 28735-28735/com.tencent.offlinewebdemo D/EgretLoader: EgretLoader(Context context)
09-24 16:43:05.378 28735-28735/com.tencent.offlinewebdemo D/EgretLoader: The context is not activity
09-24 16:43:05.390 28735-28735/com.tencent.offlinewebdemo D/EgretLoader: EgretLoader(Context context)
09-24 16:43:05.390 28735-28735/com.tencent.offlinewebdemo D/EgretLoader: The context is not activity
09-24 16:43:05.393 28735-28735/com.tencent.offlinewebdemo I/MainActivity: OfflineWebManager initStatusCallback isSuccess=false
09-24 16:43:05.393 28735-28735/com.tencent.offlinewebdemo D/OfflineWebPkgUpdate: localVersionCode =1
09-24 16:43:05.394 28735-28735/com.tencent.offlinewebdemo D/OfflineWebPkgUpdate: reqNativeWebDownloadPkg call req
09-24 16:43:05.420 28735-28771/com.tencent.offlinewebdemo E/HAL: hw_get_module_by_class: module name gralloc
09-24 16:43:05.420 28735-28771/com.tencent.offlinewebdemo E/HAL: hw_get_module_by_class: module name gralloc
09-24 16:43:12.549 28735-28735/com.tencent.offlinewebdemo E/MainActivity: Offline web init failed!
09-24 16:43:12.579 28735-28735/com.tencent.offlinewebdemo I/Toast: Show toast from OpPackageName:com.tencent.offlinewebdemo, PackageName:com.tencent.offlinewebdemo
09-24 16:43:12.681 28735-28771/com.tencent.offlinewebdemo V/RenderScript: 0x558d88a7c0 Launching thread(s), CPUs 6
```

**Comment by kangear** [comment]
webtemplate.zip 需要解压到`/sdcard/nativeweb`目录下就可以了，会跟着遇到`Error inflating class ImageView`，按照https://stackoverflow.com/a/50379554/2193455的方法可以解决。

**Comment by perqin** [comment]
离线UI模版的接入指南可以在这里参考：[https://dingdang.qq.com/doc/page/305](https://dingdang.qq.com/doc/page/305)；渲染失败的问题已经在demo中修复并提交了，感谢指出。
